### ISSUE TITLE
Issue with Replicating ImageNet Results (Pitome vs. Tome)

### ISSUE THREAD

**Issue by damugongzai** [hchautran/PiToMe#3]
Hi Author's,

I hope you're doing well! I'm trying to replicate the results from your paper on ImageNet, but I’m running into some issues. It seems like the results I'm getting aren't quite the same as what’s reported. The results for Pitome seem to be consistent with Tome, but there’s a noticeable difference when trying to replicate the full ImageNet results. I was wondering if you could share any additional details or clarifications on the implementation that might help?

Thanks in advance for your help!
![图片1](https://github.com/user-attachments/assets/96a430cf-d590-4863-9527-3cfdd6977626)

**Comment by Leo-Thomas** [comment]
Dear authors,

I’d like to reopen this issue as I’m encountering similar challenges when attempting to replicate the results on ImageNet from your paper. My results show noticeable differences compared to what’s reported, and I’m unsure if I might be missing some important details in the implementation.

Could you provide any additional insights or clarifications that might help address these discrepancies? Any guidance would be greatly appreciated.

![Image](https://github.com/user-attachments/assets/27cc1bbe-c1d7-44f1-af97-ea127616b3c0)

**Comment by hchautran** [comment]
Hi Thomas, thanks for checking in our work. Could you help check if this
issue occurs in other tasks? Just want to ensure it’s not a problem with
the algorithms but possibly stemming from our data processing pipeline.

**Comment by Leo-Thomas** [comment]
Dear Authors,

I have already done the tests with the other tasks.

*1. Text classification *

The evaluation showed errors in most of the models with pitome. The most
common error is:

    return forward_call(*args, **kwargs)
  File "/home/leo.ramos/token/PiToMe/algo/pitome/patch/bert.py", line 57,
in forward
    attention_mask = merge_attention_mask(merge,
attention_mask=attention_mask[..., None]).view(B, T)
  File "/home/leo.ramos/token/PiToMe/algo/pitome/merge.py", line 283, in
merge_attention_mask
    attention_mask = merge(attention_mask, mode="amax")
  File "/home/leo.ramos/token/PiToMe/algo/pitome/merge.py", line 216, in
merge
    B, T, C = x.shape
ValueError: too many values to unpack (expected 3)

This is repeated with almost all models in pitome. Only dct seems to be the
one that works correctly, so it has not been possible to evaluate
everything in the paper and compare.

[image: image.png]
[image: image.png]
[image: image.png]
[image: image.png]

*2. Image text retrieval*

In this case, the results are a bit closer, but there are still
inconsistencies. For example, the ***@***.*** and ***@***.*** in PiToMe Blip2 Flickr30k
r=0.95 seems to be lower than reported:

[image: image.png]

*3. Image classification.*

I did new evaluations using MAE and there are also inconsistencies there on
image classification. In fact, in my tests, ToMe is superior to PiToMe:

[image: image.png]
[image: image.png]

Overall, as you can see, there are some problems and inconsistencies, but
mostly with image classification. Any help is welcome.

Best,

--
*Leo Thomas Ramos*
